// frontend/src/services/pdf/SimplifiedPDFGenerator.ts
//
// Simplified + plain-text PDF generators for legacy/low-memory devices.
// Extracted in Phase 2 Tier 3B step 4. These are the fallback paths called
// by all three frozen version methods (v1.0.0/v1.1.0/v1.2.0) when a device
// is flagged as 2012-era or when full generation fails.
//
// Output is byte-identical to the originals — `WarningPDFData` is imported
// as a type (no runtime cycle) and the function bodies are unchanged.

import Logger from '../../utils/logger';
import type { WarningPDFData } from '../PDFGenerationService';

/**
 * Simplified PDF generation for 2012-era devices.
 * Minimal memory usage, no images, simple layout. Falls back to
 * {@link generatePlainTextPDF} on error.
 */
export async function generateSimplifiedPDF(data: WarningPDFData): Promise<Blob> {
  try {
    Logger.debug('🚨 Generating simplified PDF for legacy device...');

    // Import minimal jsPDF configuration
    const { default: jsPDF } = await import('jspdf');

    const doc = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
      compress: true
    });

    // Simple layout variables
    let currentY = 20;
    const margin = 15;
    const lineHeight = 6;

    // Basic font only
    doc.setFont('helvetica', 'normal');

    // 1. Simple Header
    doc.setFontSize(16);
    doc.text('DISCIPLINARY WARNING', margin, currentY);
    currentY += lineHeight * 2;

    // 2. Organization (text only)
    doc.setFontSize(12);
    if (data.organization?.name) {
      doc.text(`Organization: ${data.organization.name}`, margin, currentY);
      currentY += lineHeight;
    }

    currentY += lineHeight;

    // 3. Employee Details (simplified)
    doc.setFontSize(11);
    doc.text('EMPLOYEE DETAILS:', margin, currentY);
    currentY += lineHeight;

    doc.setFontSize(10);
    const employeeLines = [
      `Name: ${data.employee.firstName} ${data.employee.lastName}`,
      `Employee ID: ${data.employee.employeeNumber}`,
      `Department: ${data.employee.department}`,
      `Position: ${data.employee.position}`
    ];

    employeeLines.forEach(line => {
      doc.text(line, margin + 5, currentY);
      currentY += lineHeight;
    });

    currentY += lineHeight;

    // 4. Warning Details (simplified)
    doc.setFontSize(11);
    doc.text('WARNING DETAILS:', margin, currentY);
    currentY += lineHeight;

    doc.setFontSize(10);
    const warningLines = [
      `Date: ${data.issuedDate.toLocaleDateString()}`,
      `Category: ${data.category}`,
      `Level: ${data.warningLevel}`,
      `Location: ${data.incidentLocation || 'Not specified'}`
    ];

    warningLines.forEach(line => {
      doc.text(line, margin + 5, currentY);
      currentY += lineHeight;
    });

    currentY += lineHeight;

    // 5. Description (with word wrapping)
    doc.setFontSize(11);
    doc.text('INCIDENT DESCRIPTION:', margin, currentY);
    currentY += lineHeight;

    doc.setFontSize(10);
    const maxWidth = 170; // mm
    const descriptionLines = doc.splitTextToSize(data.description, maxWidth);

    descriptionLines.forEach((line: string) => {
      if (currentY > 270) { // Near bottom of page
        doc.addPage();
        currentY = 20;
      }
      doc.text(line, margin + 5, currentY);
      currentY += lineHeight;
    });

    currentY += lineHeight * 2;

    // 6. Signatures (simple text fields)
    if (currentY > 240) {
      doc.addPage();
      currentY = 20;
    }

    doc.setFontSize(11);
    doc.text('SIGNATURES:', margin, currentY);
    currentY += lineHeight * 2;

    doc.setFontSize(10);

    // Manager signature
    doc.text('Manager: ________________________', margin, currentY);
    currentY += lineHeight;
    doc.text(`Date: ${data.issuedDate.toLocaleDateString()}`, margin, currentY);
    currentY += lineHeight * 3;

    // Employee signature
    doc.text('Employee: _______________________ ', margin, currentY);
    currentY += lineHeight;
    doc.text('Date: _______________', margin, currentY);

    // 7. Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.text('Generated by HR System - Simplified for mobile device', margin, pageHeight - 10);

    Logger.debug('✅ Simplified PDF generation completed');

    // Force memory cleanup
    const blob = doc.output('blob');

    // Hint for garbage collection on legacy devices
    if ((window as any).gc) {
      setTimeout(() => (window as any).gc(), 100);
    }

    return blob;

  } catch (error) {
    Logger.error('❌ Simplified PDF generation failed:', error);

    // Fallback: Generate even simpler text-based PDF
    return generatePlainTextPDF(data);
  }
}

/**
 * Plain-text PDF fallback for very limited devices.
 * Absolute minimal PDF for extreme cases — last-resort path called when
 * {@link generateSimplifiedPDF} itself throws.
 */
export async function generatePlainTextPDF(data: WarningPDFData): Promise<Blob> {
  try {
    const { default: jsPDF } = await import('jspdf');
    const doc = new jsPDF();

    doc.setFontSize(12);
    let currentY = 20;
    const lineHeight = 10;

    const lines = [
      'DISCIPLINARY WARNING',
      '',
      `Employee: ${data.employee.firstName} ${data.employee.lastName}`,
      `Date: ${data.issuedDate.toLocaleDateString()}`,
      `Category: ${data.category}`,
      `Level: ${data.warningLevel}`,
      '',
      'Description:',
      data.description,
      '',
      'This is a simplified version generated for older devices.'
    ];

    lines.forEach(line => {
      if (currentY > 280) {
        doc.addPage();
        currentY = 20;
      }
      doc.text(line, 20, currentY);
      currentY += lineHeight;
    });

    return doc.output('blob');
  } catch (error) {
    Logger.error('❌ Even plain text PDF failed:', error);
    throw new Error('PDF generation not supported on this device');
  }
}
